baseURL = 'https://learnrobotics.com.mx/'
languageCode = 'es-mx'
title = 'LearnRobotics'
theme = "custom"

[params]
openGraph = true
section5 = true

  [params.navbarlogo]
  image = "logos/logo.png"
  link = "/"

  [params.font]
  name = "Open Sans"
  sizes = [ 400, 600 ]

  [params.hero]
  title = "¡Ayúdanos a impactar a más gente!"
  subtitle = "Súmate a esta causa para tener un mejor México."
  buttontext = "¡Contáctanos!"
  buttonlink = "#"
  image = "illustrations/expo.png"
  clientlogos = [ "evolutionup", "aouk", "dow", "e9", "simplewater" ]

  [[params.navbar]]
  title = "¿Quienes somos?"
  url = "/"

  [[params.navbar]]
  title = "Academy"
  url = "https://aouk.com.mx"

  [[params.navbar]]
  title = "Proyectos"

    [[params.navbar.sublinks]]
    title = "TUFD"
    url = "/"

    [[params.navbar.sublinks]]
    title = "REDI"
    url = "/"

    [[params.navbar.sublinks]]
    title = "Discovery"
    url = "/"

    [[params.navbar.sublinks]]
    title = "ThinkAhead"
    url = "https://www.instagram.com/think.ahead/"

  [[params.navbar]]
  title = "¡Contáctanos!"
  url = "/"
  button = true

  [params.section1]
  title = "Great power comes"
  subtitle = "with great responsibility"

    [[params.section1.tiles]]
    title = "App builder"
    icon = "mouse-globe"
    text = "This is some explanatory text that is on two rows"
    url = "/"
    buttonText = "Free trial"

    [[params.section1.tiles]]
    title = "Cloud integration"
    icon = "laptop-cloud"
    text = "This is some explanatory text that is on two rows"
    url = "/"
    buttonText = "Get started"

    [[params.section1.tiles]]
    title = "Add-ons & plugins"
    icon = "plug-cloud"
    text = "This is some explanatory text that is on two rows"
    url = "/"
    buttonText = "Get started"
 [params.section3]
  title = "One platform"
  subtitle = "To rule them all"
  image = "illustrations/mockups/app-mockup.png"
  buttonText = "Get started"
  buttonLink = "#"

  [params.section4]
  title = "Algunos testimonios"
  subtitle = "A continuación podrás escuchar los testimonios de algunas personas que han sido impactadas por LearnRobotics y ayudarán al desarrollo de México en temas de STEM."

    [[params.section4.clients]]
    name = "Luis Hernandez"
    quote = "La tecnología es lo del futuro, por eso es importante apostarle a la programación. Te abre muchas puertas y el poder de explotar tu creatividad, creando casi cualquier cosa."
    job = "Colaborador de LearnRobotics"
    img = 1

    [[params.section4.clients]]
    name = "Matias Piedra"
    quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
    job = "Colaborador de LearnRobotics"
    img = 2

    [[params.section4.clients]]
    name = "Eric Garcia"
    quote = "Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at."
    job = "EvolutionUp CEO"
    img = 3

  [params.footer]
  logo = "logo.png"
  socialmediatitle = "Follow Us"
  bulmalogo = false

    [[params.footer.socialmedia]]
    link = "https://github.com/mcn2004"
    icon = "github"

    [[params.footer.socialmedia]]
    link = "https://facebook.com/#"
    icon = "facebook"

    [[params.footer.socialmedia]]
    link = "https://twitter.com/macnolo2004"
    icon = "twitter"

    [[params.footer.socialmedia]]
    link = "https://bitbucket.org/#"
    icon = "bitcoin"

[params.footer.quicklinks.column1]
title = "Proyectos"

  [[params.footer.quicklinks.column1.links]]
  text = "ThinkAhead"
  link = "/"

  [[params.footer.quicklinks.column1.links]]
  text = "TUFD"
  link = "/"

  [[params.footer.quicklinks.column1.links]]
  text = "Discovery"
  link = "/"

  [[params.footer.quicklinks.column1.links]]
  text = "Aprendiendo a Programar"
  link = "/"

  [[params.footer.quicklinks.column1.links]]
  text = "REDI"
  link = "/agb"

#[params.footer.quicklinks.column3]
#title = "Blog"

#  [[params.footer.quicklinks.column3.links]]
#  text = "Latest news"
#  link = "/blog/first"

#  [[params.footer.quicklinks.column3.links]]
#  text = "Tech articles"
#  link = "/blog/second"
